### Login user
POST http://{{apiURL}}:9000/auth/login
Content-Type: application/json

{
  "login": "testUser123",
  "password": "Passss_1"
}

### Login MAIN ADMIN
POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

### Login TEST ADMIN
POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}

### Get users without jwt
GET http://localhost:9000/auth/users

### Reg new user
POST http://localhost:9000/auth/reg
Content-Type: application/json

{
  "login": "testUser123",
  "password": "Passss_1",
  "countryId": "61f988955d289d4cb3c483ad"
}

### Reg new admin
POST http://localhost:9000/auth/regAdm
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}

### Reg wrong route
POST http://localhost:9000/auth/regAdm123456
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}
