// ------------ AUTH ------------

### Login user
POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "login": "testUser",
  "password": "123456"
}

### Login MAIN ADMIN
POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

### Login TEST ADMIN
POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}

### Get users without jwt
GET http://localhost:9000/auth/users

### Reg new user
POST http://localhost:9000/auth/reg
Content-Type: application/json

{
  "login": "testUser1",
  "password": "123456"
}

### Reg new admin
POST http://localhost:9000/auth/regAdm
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}

### Reg wrong route
POST http://localhost:9000/auth/regAdm123456
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}

### Get Years
GET http://localhost:9000/api/years

### Get Countries
GET http://localhost:9000/api/countries

### Get Ranks
GET http://localhost:9000/api/ranks

// ------------ ADD DATA------------

### Add new year
POST http://localhost:9000/api/years
Content-Type: application/json

{
  "date": "1918"
}

### Add new country
POST http://localhost:9000/api/countries
Content-Type: application/json

{
  "name": "Austria-Hungary Empire"
}

### Add new rank
POST http://localhost:9000/api/ranks
Content-Type: application/json

{
    "name": "Feldmarschall",
    "points": 1000,
    "img": "https://pixy.org/images/placeholder.png",
    "countryId": "61f988955d289d4cb3c483ad"
}

