// ------------ AUTH ------------

### Login user request
POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "login": "testUser",
  "password": "123456"
}

### Login admin request
POST http://localhost:9000/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

### Get users without jwt
GET http://localhost:9000/auth/users

// ------------ GET DATA------------

### Get Years
GET http://localhost:9000/api/years

### Get Countries
GET http://localhost:9000/api/countries

### Get Ranks
GET http://localhost:9000/api/ranks

// ------------ ADD DATA------------

### Add new year
POST http://localhost:9000/api/years
Content-Type: application/json

{
  "date": "1918"
}

### Add new country
POST http://localhost:9000/api/countries
Content-Type: application/json

{
  "name": "Austria-Hungary Empire"
}

### Add new rank
POST http://localhost:9000/api/ranks
Content-Type: application/json

{
    "name": "Private",
    "points": 100,
    "img": "https://pixy.org/images/placeholder.png",
    "countryId": "61f987b85d289d4cb3c483aa"
}

