### Rank
POST {{localhost}}/ranks
Content-Type: application/json

{
  "name": "Feldmarschall",
  "points": 1000,
  "img": "https://pixy.org/images/placeholder.png",
  "countryId": "61f988955d289d4cb3c483ad"
}

### Achievement
POST {{localhost}}/achievements
Content-Type: application/json

{
  "name": "Achievement 7",
  "points": 100
}

### Test Theme
POST {{localhost}}/tests-themes
Content-Type: application/json

{
  "name": "Как всё это началось",
  "achievementId": "6276950f78d62971b8d5b617"
}

### Test Question
POST {{localhost}}/tests-questions
Content-Type: application/json

{
  "text": "Где произошло сие вопиющее убийство?",
  "testThemeId": "627a7b67d4c5b1d12abf3094"
}

### Test Answer
POST {{localhost}}/tests-answers
Content-Type: application/json

{
  "text": "Около продовольственного магазина 'Деликатесы Морица Шиллера'",
  "isTrue": true,
  "points": 20,
  "testQuestionId": "627a7cbdd4c5b1d12abf309d"
}

### Event
POST {{localhost}}/events
Content-Type: application/json

{
  "title": "Начало войны",
  "text": "<h5>Началось всё в 1914 году</h5>*img-Подпись под картинкой*<h3>Потом что-то ещё случилось</h3>*img-Подпись под картинкой*<p><b>Жирный текст</b> <i>курсивный текст</i> <u>подчеркнутый текст</u></p>",
  "images": [
    "https://dic.academic.ru/pictures/wiki/files/102/franz_ferdinand.jpg",
    "https://dic.academic.ru/pictures/wiki/files/102/franz_ferdinand.jpg",
    "https://dic.academic.ru/pictures/wiki/files/102/franz_ferdinand.jpg"
  ],
  "yearId": "61ebe62d36a81045af82dcca"
}