### Year
POST {{localhost}}/years
Content-Type: application/json

{
  "date": "1919"
}

### Country
POST{{localhost}}/countries
Content-Type: application/json

{
  "name": "Austria-Hungary Empire"
}

### Rank
POST {{localhost}}/ranks
Content-Type: application/json

{
  "name": "Feldmarschall",
  "points": 1000,
  "img": "https://pixy.org/images/placeholder.png",
  "countryId": "61f988955d289d4cb3c483ad"
}

### Achievement
POST {{localhost}}/achievements
Content-Type: application/json

{
  "name": "Achievement 3",
  "description": "{{loren-ipsum-10}}",
  "points": 100
}