### Login user
POST {{localhost}}/auth/login
Content-Type: application/json

{
  "login": "testUser",
  "password": "Pass_1"
}

### Login MAIN ADMIN
POST{{localhost}}/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

### Login TEST ADMIN
POST {{localhost}}/auth/login
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}

### Get users without jwt
GET {{localhost}}/auth/users

### Reg new user
POST {{localhost}}/auth/reg
Content-Type: application/json

{
  "login": "testUser",
  "password": "Pass_1",
  "countryId": "61f988955d289d4cb3c483ad"
}

### Reg new admin
POST {{localhost}}/auth/reg-adm
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}

### Reg wrong route
POST {{localhost}}/auth/reg-adm123456
Content-Type: application/json

{
  "login": "testAdmin",
  "password": "123456"
}
