### Get Years
GET {{localhost}}/years

### Get Countries
GET {{localhost}}/countries

### Get Ranks
GET {{localhost}}/ranks

### Get test
GET {{localhost}}/test

### Get Achievements
GET {{localhost}}/achievements

### Get Surveys
GET {{localhost}}/surveys